table vw_hourly_analysis
	lineageTag: abba6e38-d8a7-43c9-ab00-f1c5195bafad

	column hour_bucket
		dataType: int64
		formatString: 0
		lineageTag: 9103b03a-ec37-42ae-94d1-116a1d3ac78e
		summarizeBy: sum
		sourceColumn: hour_bucket

		annotation SummarizationSetBy = Automatic

	column txns
		dataType: int64
		formatString: 0
		lineageTag: f888868a-3e1d-4aa4-8cdd-6ccbaba0a6cf
		summarizeBy: sum
		sourceColumn: txns

		annotation SummarizationSetBy = Automatic

	column fraud
		dataType: int64
		formatString: 0
		lineageTag: 9d00a3a6-7bb3-4ea7-97a8-3ea72be60529
		summarizeBy: sum
		sourceColumn: fraud

		annotation SummarizationSetBy = Automatic

	column fraud_rate_pct
		dataType: double
		lineageTag: 2e599215-3168-4634-b3d8-3240420c626d
		summarizeBy: sum
		sourceColumn: fraud_rate_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure HourlyTxnsSum = SUM(vw_hourly_analysis[txns])
		lineageTag: c05eff27148b7cce9750
		formatString: #,0
	measure FraudRatePctAvg = AVERAGE(vw_hourly_analysis[fraud_rate_pct])
		lineageTag: 0f9dcac7a59543ef6be2
		formatString: 0.0000


	partition vw_hourly_analysis = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\faiza\Documents\Default Project\FinGuard\data\dashboard_export\vw_hourly_analysis.csv"), [Delimiter = ",", Columns = 4, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"hour_bucket", Int64.Type}, {"txns", Int64.Type}, {"fraud", Int64.Type}, {"fraud_rate_pct", type number}}, "en-US")
				in
				  #"Changed column type"

