table vw_model_test_confusion
	lineageTag: baefde35-a60d-43fa-bf22-6e33294ee75b

	column model_name
		dataType: string
		lineageTag: 0a711bf6-3e55-47c5-9fcc-1e20a7adf032
		summarizeBy: none
		sourceColumn: model_name

		annotation SummarizationSetBy = Automatic

	column test_rows
		dataType: int64
		formatString: 0
		lineageTag: 53bcd323-75f2-4d30-89b0-43473040ecf6
		summarizeBy: sum
		sourceColumn: test_rows

		annotation SummarizationSetBy = Automatic

	column tp
		dataType: int64
		formatString: 0
		lineageTag: f1eaf83f-ddaf-48d1-8373-083cad50dc14
		summarizeBy: sum
		sourceColumn: tp

		annotation SummarizationSetBy = Automatic

	column fp
		dataType: int64
		formatString: 0
		lineageTag: c0b8e294-54cb-4718-b204-5aad9147292a
		summarizeBy: sum
		sourceColumn: fp

		annotation SummarizationSetBy = Automatic

	column fn
		dataType: int64
		formatString: 0
		lineageTag: cea68622-f689-4ca5-9078-b3ce37f7937e
		summarizeBy: sum
		sourceColumn: fn

		annotation SummarizationSetBy = Automatic

	column tn
		dataType: int64
		formatString: 0
		lineageTag: 4a7c75fa-fedb-42ed-9774-3636c2046bd5
		summarizeBy: sum
		sourceColumn: tn

		annotation SummarizationSetBy = Automatic

	column precision_pct
		dataType: double
		lineageTag: 3938c47c-45c6-4a2c-84b8-9b5f5d53a76f
		summarizeBy: sum
		sourceColumn: precision_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column recall_pct
		dataType: double
		lineageTag: 49d922eb-2981-427c-aa44-932fd2a49626
		summarizeBy: sum
		sourceColumn: recall_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column f1_pct
		dataType: double
		lineageTag: 96b0a08c-8c5d-4634-9c4b-24504fb1bbe0
		summarizeBy: sum
		sourceColumn: f1_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PrecisionPctSum = SUM(vw_model_test_confusion[precision_pct])
		lineageTag: 4356b46df98cbb4c847a
		formatString: 0.00
	measure RecallPctSum = SUM(vw_model_test_confusion[recall_pct])
		lineageTag: af9dca990366d7b96baa
		formatString: 0.00
	measure F1PctSum = SUM(vw_model_test_confusion[f1_pct])
		lineageTag: 934d325401145e7bd739
		formatString: 0.00


	partition vw_model_test_confusion = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\faiza\Documents\Default Project\FinGuard\data\dashboard_export\vw_model_test_confusion.csv"), [Delimiter = ",", Columns = 9, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"model_name", type text}, {"test_rows", Int64.Type}, {"tp", Int64.Type}, {"fp", Int64.Type}, {"fn", Int64.Type}, {"tn", Int64.Type}, {"precision_pct", type number}, {"recall_pct", type number}, {"f1_pct", type number}}, "en-US")
				in
				  #"Changed column type"

