table vw_transaction_monitoring
	lineageTag: b888a622-e877-4461-9b65-eb99b438eeb8

	column transaction_id
		dataType: int64
		formatString: 0
		lineageTag: a3bcfd4b-fb25-49ed-bd18-678b2098916d
		summarizeBy: sum
		sourceColumn: transaction_id

		annotation SummarizationSetBy = Automatic

	column hour_since_start
		dataType: int64
		formatString: 0
		lineageTag: 6ab45595-4edc-4a01-b32e-27e4aaf451fb
		summarizeBy: sum
		sourceColumn: hour_since_start

		annotation SummarizationSetBy = Automatic

	column hour_of_day
		dataType: double
		lineageTag: 52d751f1-c2ea-4a71-ae1d-7bf642949e81
		summarizeBy: sum
		sourceColumn: hour_of_day

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column day_index
		dataType: int64
		formatString: 0
		lineageTag: 84e8575d-2da5-4822-a3bd-d5d5187ba17a
		summarizeBy: sum
		sourceColumn: day_index

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: double
		lineageTag: 418d241e-5999-4cfb-8eb2-7e0a590f3e97
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column class
		dataType: int64
		formatString: 0
		lineageTag: ca65ae7d-0dd0-4dec-925d-2bd041e3596d
		summarizeBy: none
		sourceColumn: class

		annotation SummarizationSetBy = Automatic

	column alert_count
		dataType: int64
		formatString: 0
		lineageTag: 87873aac-e5b0-426e-8f8b-228b13282a5f
		summarizeBy: sum
		sourceColumn: alert_count

		annotation SummarizationSetBy = Automatic

	column max_risk_score
		dataType: double
		lineageTag: 56199248-94c5-4281-a61b-76645ac42dec
		summarizeBy: sum
		sourceColumn: max_risk_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column alert_sources
		dataType: string
		lineageTag: 367c436c-1af5-428d-819d-d89051e93a26
		summarizeBy: none
		sourceColumn: alert_sources

		annotation SummarizationSetBy = Automatic

	column rf_probability_test
		dataType: double
		lineageTag: f57f26dc-592b-4e13-857d-e62324f72c69
		summarizeBy: sum
		sourceColumn: rf_probability_test

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition vw_transaction_monitoring = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\faiza\Documents\Default Project\FinGuard\data\dashboard_export\vw_transaction_monitoring.csv"), [Delimiter = ",", Columns = 10, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"transaction_id", Int64.Type}, {"hour_since_start", Int64.Type}, {"hour_of_day", type number}, {"day_index", Int64.Type}, {"amount", type number}, {"class", Int64.Type}, {"alert_count", Int64.Type}, {"max_risk_score", type number}, {"alert_sources", type text}, {"rf_probability_test", type number}}, "en-US")
				in
				  #"Changed column type"

